# Generated by Django 3.2 on 2021-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=12, upload_to='post_img/'),
            preserve_default=False,
        ),
    ]
